version: '3'

volumes:
  postgres-data:
    driver: local
  app-gems:
    driver: local

services:
  db:
    image: postgres:9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web: &app_base
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
      - app-gems:/usr/local/bundle
    links:
      - db
    depends_on:
      - db
    stdin_open: true
    environment: &app_environment
      RACK_ENV: development
      RAILS_ENV: development
